### ISSUE TITLE
FinalTest方法少了个Test注解

### ISSUE THREAD

**Issue by pandorawanz** [hcsp/correct-final#11]
本地运行的测试没生效
`[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0`

原因应该是FinalTest的test()方法上漏了个`@Test`注解

**Comment by blindpirate** [comment]
感谢反馈。

Closed by https://github.com/hcsp/correct-final/commit/3cf54c43e5866bfd5f12962e09559d21f13ecfc1
